name: AfkScroll
main: io.github.currychris.afkscroll.AfkScroll
version: 0.0.1
author: ItsCrys
commands:
  afkscroll:
    description: This is a demo command.
    usage: /afkscroll
    permission: afkscroll
    permission-message: You don't have afkscroll